### ISSUE TITLE
门卡死问题

### ISSUE THREAD

**Issue by buger404** [buger404/Morizero#13]
从雪兰病房出去后进入兮的病房的门，回到雪兰病房门口后，再进去病房会导致卡死。

**Comment by SweetIceLolly** [comment]
对不起我把他reopen

**Comment by buger404** [comment]
![{XVX6PN`M5ZNCHS3~%F@MYS](https://user-images.githubusercontent.com/42364915/166132369-de0f7e04-7e73-4549-b75d-6fc93dda4293.png)
